# Generated by Django 3.0.2 on 2020-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped Number'), ('in_progress', 'In Prigress'), ('canceled', 'Canceled'), ('delivered', 'delivered')], default='shipped', max_length=256),
        ),
    ]
